// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7L2yMLeg8V7Z3yNvE0jqrdNPX-whjNyI',
    appId: '1:64549818782:web:d4cd9c3c57b586f993468f',
    messagingSenderId: '64549818782',
    projectId: 'fir-flutter-codelab-ce7d2',
    authDomain: 'fir-flutter-codelab-ce7d2.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ce7d2.appspot.com',
    measurementId: 'G-QNDLTPJJ4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm0Ewr127Ir-QIPaV3Le-LZTmz8XzewYs',
    appId: '1:64549818782:android:1171a0ff48cc152693468f',
    messagingSenderId: '64549818782',
    projectId: 'fir-flutter-codelab-ce7d2',
    storageBucket: 'fir-flutter-codelab-ce7d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzfrmK4q3miZOpUR10dXgcCLeF6IHOG9s',
    appId: '1:64549818782:ios:d7e2fd7adbc1263293468f',
    messagingSenderId: '64549818782',
    projectId: 'fir-flutter-codelab-ce7d2',
    storageBucket: 'fir-flutter-codelab-ce7d2.appspot.com',
    iosBundleId: 'com.example.appdev2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzfrmK4q3miZOpUR10dXgcCLeF6IHOG9s',
    appId: '1:64549818782:ios:d7e2fd7adbc1263293468f',
    messagingSenderId: '64549818782',
    projectId: 'fir-flutter-codelab-ce7d2',
    storageBucket: 'fir-flutter-codelab-ce7d2.appspot.com',
    iosBundleId: 'com.example.appdev2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7L2yMLeg8V7Z3yNvE0jqrdNPX-whjNyI',
    appId: '1:64549818782:web:92fec4f1b1c10fbd93468f',
    messagingSenderId: '64549818782',
    projectId: 'fir-flutter-codelab-ce7d2',
    authDomain: 'fir-flutter-codelab-ce7d2.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ce7d2.appspot.com',
    measurementId: 'G-2PD2KZR2NZ',
  );
}
